--- Sentencias SQL para la creaci�n del esquema de parranderos
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- USO
-- Copie el contenido de este archivo en una pesta�a SQL de SQL Developer
-- Ejec�telo como un script - Utilice el bot�n correspondiente de la pesta�a utilizada

-- Creaci�n del secuenciador
create sequence centro_comercial_sequence;

-- Creaaci�n de la tabla TIPOBEBIDA y especificaci�n de sus restricciones
CREATE TABLE CENTRO_COMERCIAL
   ( 
	NOMBRE VARCHAR2(255 BYTE), 
	AFORO FLOAT NOT NULL,
    CONSTRAINT centro_comercial_pk PRIMARY KEY(NOMBRE));

CREATE TABLE ESPACIO
(
  ID_ESPACIO NUMBER NOT NULL,
  HORARIO_APERTURA_EMPLEADOS TIMESTAMP NOT NULL,
  HORARIO_APERTURA_CLIENTES TIMESTAMP NOT NULL,
  HORARIO_CIERRE_CLIENTES TIMESTAMP NOT NULL,
  AFORO_ACTUAL INT NOT NULL,
  AFORO_TOTAL INT NOT NULL,
  ESTADO VARCHAR2(255 BYTE),
  CONSTRAINT espacio_pk PRIMARY KEY (ID_ESPACIO));

ALTER TABLE ESPACIO
ADD CONSTRAINT ck_estado
CHECK(ESTADO IN ('Desocupado','Verde','Deshabilitado','Rojo','Naranja'))
ENABLE;
  
 CREATE TABLE LOCAL_COMERCIAL
(
  IDESPACIO NUMBER  NOT NULL,
  ID_LOCAL NUMBER NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  NOMBRE_EMPRESA VARCHAR2(255 BYTE) NOT NULL,
  AREA FLOAT NOT NULL,
  TIPO_ESTABLECIMIENTO VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT local_comercialpk PRIMARY KEY(ID_LOCAL)) ;
ALTER TABLE LOCAL_COMERCIAL
ADD CONSTRAINT fk_local
    FOREIGN KEY (IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;
  CREATE TABLE PARQUEADERO(
  IDESPACIO NUMBER NOT NULL,
  ID_PARQUEADERO NUMBER NOT NULL,
  CAPACIDAD FLOAT NOT NULL,
  CONSTRAINT parqueadero_pk PRIMARY KEY(ID_PARQUEADERO)
  );
  ALTER TABLE PARQUEADERO
  ADD CONSTRAINT fk_parqueadero
    FOREIGN KEY (IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;
  
  CREATE TABLE BAÑO(
  IDESPACIO NUMBER NOT NULL,
  ID_BAÑO NUMBER NOT NULL,
  NUMERO_SANITARIOS INT NOT NULL,
  CONSTRAINT baño_pk PRIMARY KEY (ID_BAÑO));
  
    ALTER TABLE BAÑO
  ADD CONSTRAINT fk_baño
    FOREIGN KEY (IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;
CREATE TABLE LECTOR
(
  ID_LECTOR NUMBER NOT NULL,
  IDESPACIO NUMBER NOT NULL,
  CONSTRAINT lector_pk PRIMARY KEY(ID_LECTOR));
ALTER TABLE LECTOR
ADD CONSTRAINT fk_espacio
    FOREIGN KEY (IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;

CREATE TABLE CARNET
(
  ID_CARNET NUMBER NOT NULL,
  CEDULA FLOAT NOT NULL,
  CONSTRAINT carnet_pk PRIMARY KEY(ID_CARNET));

  
CREATE TABLE VISITA
(
  FECHAYHORA_OP TIMESTAMP NOT NULL,
  TIPO_OP VARCHAR2(255 BYTE) NOT NULL,
  HORAFIN_OP TIMESTAMP NOT NULL,
  IDLECTOR NUMBER NOT NULL,
  IDCARNET NUMBER NOT NULL,
  IDESPACIO NUMBER NOT NULL,
  CONSTRAINT visita_pk PRIMARY KEY(IDLECTOR, IDCARNET, IDESPACIO,TIPO_OP,FECHAYHORA_OP));
  
ALTER TABLE VISITA
ADD CONSTRAINT fk_visita_lector
    FOREIGN KEY(IDLECTOR)
    REFERENCES LECTOR(ID_LECTOR)
ENABLE;

ALTER TABLE VISITA
ADD CONSTRAINT fk_visita_carnet
    FOREIGN KEY(IDCARNET)
    REFERENCES carnet(ID_CARNET)
ENABLE;

ALTER TABLE VISITA
ADD CONSTRAINT fk_visita_espacio
    FOREIGN KEY(IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;


CREATE TABLE VISITANTE
( CEDULA FLOAT NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  TELEFONO FLOAT NOT NULL,
  NOMBRE_CONTACTO VARCHAR2(255 BYTE) NOT NULL,
  TELEFONO_CONTACTO FLOAT NOT NULL,
  CODIGO_QR VARCHAR2(255 BYTE) NOT NULL,
  CORREO VARCHAR2(255 BYTE) NOT NULL,
  HORARIO_DISPONIBLE TIMESTAMP NOT NULL,
  TIPO_VISITANTE VARCHAR2(255 BYTE) NOT NULL,
  IDESPACIO NUMBER NOT NULL,
  ESTADO VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT visitante_pk PRIMARY KEY(CEDULA));

ALTER TABLE VISITANTE
ADD CONSTRAINT ck_tipo_visitante
    CHECK(TIPO_VISITANTE IN ('Empleado','Vigilancia','Aseo','Mantenimiento','Clientes','Domiciliarios','Administrador_centro','Administrador_local'))
ENABLE;

ALTER TABLE VISITANTE
ADD CONSTRAINT ck_estado_visitante
    CHECK(ESTADO IN ('Positivo', 'Rojo', 'Naranja','Verde'))
ENABLE;

ALTER TABLE VISITANTE
ADD CONSTRAINT fk_espacio_visitante
    FOREIGN KEY(IDESPACIO)
    REFERENCES espacio(ID_ESPACIO)
ENABLE;

  ALTER TABLE CARNET
  ADD CONSTRAINT fk_cedula
  FOREIGN KEY (CEDULA)
  REFERENCES   visitante(CEDULA)
  ENABLE;
COMMIT;
