---Sentencia para local mas solicitado------
CREATE TABLE LOCALES_VISITADOS(
NOMBRE VARCHAR2(255 BYTE) NOT NULL,
TIPO_ESTABLECIMIENTO VARCHAR2(255 BYTE) NOT NULL,
CONTADOR_VISITAS NUMBER NOT NULL,
FECHA_SEMANA DATE NOT NULL
);
DECLARE
V_ITERATOR NUMBER;
V_DATE DATE;
BEGIN
V_ITERATOR:= 0;
V_DATE:= TO_DATE('01/01/2020', 'DD/MM/YYYY');
LOOP
V_ITERATOR:= V_ITERATOR+7;
INSERT INTO LOCALES_VISITADOS
SELECT local_comercial.nombre, local_comercial.tipo_establecimiento as Tipo,contadorVisitas,V_DATE
FROM(SELECT IDESPACIO as IDESPACIOXD, COUNT( IDCARNET)as contadorVisitas
    FROM VISITA
    WHERE VISITA.FECHAYHORA_OP BETWEEN V_DATE AND V_DATE+V_ITERATOR
    GROUP BY IDESPACIO
    HAVING COUNT( IDCARNET)>0)
    INNER JOIN LOCAL_COMERCIAL ON IDESPACIOXD=LOCAL_COMERCIAL.idespacio
    WHERE ROWNUM<=1
    ORDER BY contadorVisitas DESC;
V_DATE:= V_DATE+V_ITERATOR+1;
    EXIT WHEN V_ITERATOR=364;
END LOOP;
END;
--ultima--
SELECT * FROM LOCALES_VISITADOS;
--Sentencia para local menos solicitado-----
--parte 1--
CREATE TABLE LOCALES_MENOS_VISITADOS(
NOMBRE VARCHAR2(255 BYTE) NOT NULL,
TIPO_ESTABLECIMIENTO VARCHAR2(255 BYTE) NOT NULL,
CONTADOR_VISITAS NUMBER NOT NULL,
FECHA_SEMANA DATE NOT NULL
);
DECLARE
V_ITERATOR NUMBER;
V_DATE DATE;
BEGIN
V_ITERATOR:= 0;
V_DATE:= TO_DATE('01/01/2020', 'DD/MM/YYYY');
LOOP
V_ITERATOR:= V_ITERATOR+7;
INSERT INTO LOCALES_MENOS_VISITADOS
SELECT local_comercial.nombre, local_comercial.tipo_establecimiento as Tipo,contadorVisitas,V_DATE
FROM(SELECT IDESPACIO as IDESPACIOXD, COUNT( IDCARNET)as contadorVisitas
    FROM VISITA
    WHERE VISITA.FECHAYHORA_OP BETWEEN V_DATE AND V_DATE+V_ITERATOR
    GROUP BY IDESPACIO
    HAVING COUNT( IDCARNET)>0)
    INNER JOIN LOCAL_COMERCIAL ON IDESPACIOXD=LOCAL_COMERCIAL.idespacio
    ORDER BY contadorVisitas ASC, V_DATE ASC;
V_DATE:= V_DATE+V_ITERATOR+1;
    EXIT WHEN V_ITERATOR=364;
END LOOP;
END;
--parte 2--
CREATE TABLE LOCALES_M_VISITADOS(
NOMBRE VARCHAR2(255 BYTE) NOT NULL,
TIPO_ESTABLECIMIENTO VARCHAR2(255 BYTE) NOT NULL,
CONTADOR_VISITAS NUMBER NOT NULL,
FECHA_SEMANA DATE NOT NULL
);
DECLARE
V_ITERATOR NUMBER;
V_DATE DATE;
BEGIN
V_ITERATOR:= 0;
V_DATE:= TO_DATE('01/01/2020', 'DD/MM/YYYY');
LOOP
V_ITERATOR:= V_ITERATOR+7;
INSERT INTO LOCALES_M_VISITADOS
SELECT * FROM LOCALES_MENOS_VISITADOS WHERE CONTADOR_VISITAS =(SELECT MIN(contador_visitas) FROM LOCALES_MENOS_VISITADOS WHERE FECHA_SEMANA BETWEEN V_DATE AND V_DATE+V_ITERATOR);
V_DATE:= V_DATE+V_ITERATOR+1;
    EXIT WHEN V_ITERATOR=364;
END LOOP;
END;
-- ultima--
SELECT DISTINCT * FROM LOCALES_M_VISITADOS;
-