--REQUERIMIENTO DE CONSULTA 1
--Para administradores de establecimientos comerciales
SELECT Carnet, VISITANTE.CEDULA, VISITANTE.NOMBRE, VISITANTE.TELEFONO, VISITANTE.NOMBRE_CONTACTO, VISITANTE.TELEFONO_CONTACTO, VISITANTE.CORREO
FROM(SELECT IDCARNET as Carnet
    FROM VISITA
    WHERE idespacio=? AND FECHAYHORA_OP BETWEEN ? AND ?)
    INNER JOIN CARNET ON CARNET.ID_CARNET=Carnet
    INNER JOIN VISITANTE ON CARNET.CEDULA=VISITANTE.CEDULA;
--Para el administrador del centro
SELECT Carnet, xs as IdEspacio, VISITANTE.CEDULA, VISITANTE.NOMBRE, VISITANTE.TELEFONO, VISITANTE.NOMBRE_CONTACTO, VISITANTE.TELEFONO_CONTACTO, VISITANTE.CORREO
FROM (SELECT IDCARNET as Carnet, IDESPACIO as xs
    FROM VISITA
    WHERE FECHAYHORA_OP BETWEEN ? AND ?)
    INNER JOIN CARNET ON CARNET.ID_CARNET=Carnet
    INNER JOIN VISITANTE ON CARNET.CEDULA=VISITANTE.CEDULA;