--RFC5 por TIPO DE VISITANTE
SELECT CedulaVis, nombre, VISITA.FECHAYHORA_OP, VISITA.TIPO_OP, VISITA.HORAFIN_OP, visita.idespacio
FROM (SELECT CEDULA as CedulaVis, NOMBRE as nombre
      FROM VISITANTE
      WHERE TIPO_VISITANTE=?) 
INNER JOIN CARNET ON carnet.cedula=CedulaVis
INNER JOIN VISITA ON CARNET.ID_CARNET=IDCARNET
WHERE visita.fechayhora_op BETWEEN ? AND ?;
--RFC5 por TIPO DE LOCAL
SELECT IdEspacioXd, nombre, COUNT(VISITA.TIPO_OP) as NumeroVisitas
FROM (SELECT IDESPACIO as IdEspacioXd, NOMBRE as nombre
      FROM LOCAL_COMERCIAL
      WHERE TIPO_ESTABLECIMIENTO='Restaurante') 
INNER JOIN VISITA ON IdEspacioXd=visita.idespacio
WHERE visita.fechayhora_op BETWEEN to_date('2020-12-14:10:00:00', 'YYYY-MM-DD:HH24:MI:SS') AND to_date('2020-12-14:16:00:00', 'YYYY-MM-DD:HH24:MI:SS')
GROUP BY IdEspacioXd, nombre;