--RFC8
SELECT VISITANTE.NOMBRE, VISITANTE.TELEFONO, VISITANTE.CORREO, idCarnetUsuario, numVisitasEseMes, mes
FROM(SELECT aidi, name, mes, idCarnetUsuario, numVisitasEseMes
FROM(SELECT aidi, name, EXTRACT(MONTH FROM CAST(FECHAYHORA_OP as DATE)) as mes, VISITA.IDCARNET as idCarnetUsuario, COUNT(VISITA.FECHAYHORA_OP) as numVisitasEseMes
FROM(SELECT IDESPACIO as aidi, NOMBRE as name
FROM LOCAL_COMERCIAL
WHERE NOMBRE='Hayes LLC')
INNER JOIN VISITA ON VISITA.IDESPACIO=aidi
GROUP BY VISITA.IDCARNET, EXTRACT(MONTH FROM CAST(FECHAYHORA_OP as DATE)), aidi, name)
WHERE numVisitasEseMes>=3)
INNER JOIN CARNET ON CARNET.ID_CARNET=idCarnetUsuario
INNER JOIN VISITANTE ON CARNET.CEDULA=VISITANTE.CEDULA AND NOT VISITANTE.TIPO_VISITANTE='Mantenimiento' AND NOT VISITANTE.TIPO_VISITANTE='Domiciliarios'
GROUP BY VISITANTE.NOMBRE, VISITANTE.TELEFONO, VISITANTE.CORREO, idCarnetUsuario, numVisitasEseMes, mes;